library:
  image: bhagwatkumar/library
#  ports:
#     - "8080:8080"
  environment:
    JDBC_DATABASE_URL: "jdbc:mysql://mysql/library_prod?useSSL=false&user=root&password=igdefault&autoReconnect=true"
    EUREKA_SERVER: discovery
    EUREKA_PORT: 1111
    GRAILS_ENV: production
    SERVER_PORT: 8080
  links:
    - mysql
    - discovery
mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: igdefault
      MYSQL_DATABASE: library_prod
ha_library:
 image: tutum/haproxy
 links:
   - library
 ports:
   - "8080:80"
employee:
  image: bhagwatkumar/employee
#  ports:
#     - "7080:7080"
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://mongodb/employee
    EUREKA_SERVER: discovery
    EUREKA_PORT: 1111
    SERVER_PORT: 7080
  links:
    - mongodb
    - discovery
mongodb:
 image: mongo
ha_employee:
 image: tutum/haproxy
 links:
   - employee
 ports:
   - "7080:80"
discovery:
      image: bhagwatkumar/discovery
      ports:
        - "1111:1111"
